[package]
name = "filedime"
version = "0.9.65"
description = "rust based file explorer."
authors = ["visnk"]
license = ""
repository = "https://github.com/visnkmr/filedime"
edition = "2021"

# [build]
# target-dir="H:\\rust_deps\\"

[profile.release]
# strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"
# lto = true
# panic = "abort"

# [lib]
# crate-type = ["dylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
local-ip-address="0.6.1"
# fs_extra= {git="https://github.com/visnkmr/fs_extra.git"} #"1.3.0"
fs_extra= {path="../fs_extra/"} #"1.3.0"
syntect="5.1.0"
# prefstore= {path="../../../rust/prefstore/prefstore"}
prefstore= {git="https://github.com/visnkmr/prefstore.git"}
tauri = { version = "1.5.4", features = [ "os-all", "devtools", "fs-read-file", "path-all", "protocol-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon="1.7.0"
# image = "0.24.6"
# image = {git="https://codeberg.org/visnk/image-rs.git"}
reqwest="0.11.24"
tokio= {version="1.36.0",features= ["macros"] }
fuzzy-matcher="0.3.7"
num_cpus="1.15.0"
rustc-hash="1.1.0"
# json="0.12.4"
# rs-drivelist = "0.9.3"
# tao = { version = "0.19.0"}
# du="0.1.1"
# gio="0.17.4"
# walkdir="2.3.3"
filesize = "0.2.0"
# jwalk="0.8.1"
# dua-cli="2.19.2"
# dirscan="1.4.1"
# markdown= {git="https://github.com/wooorm/markdown-rs.git"}
opener="0.6.1"
comrak="0.18.0"
# contrie="0.1.4"
chrono="0.4.24"
# strsim="0.10.0"
# notify="5.1.0"
filetime="0.2.21"
# rust_search = "2.0.0"
# infer="0.13.0"
# indicatif="0.17.3"
# radix_trie = "0.2.1"
# rusync="0.7.2"
libc="0.2.144"
sysinfo="0.29.0"
ignore="0.4.20"
dirs="5.0.1"
regex="1.10.2"
# gtk = "0.15.5"
# gio = "0.18.4"
# ollama-rs = {version="0.1.7",features= ["stream"] }
# warp="0.3.6"
include_dir = "0.7.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
